# Generated by Django 5.0.3 on 2024-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='sproduct1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('review', models.TextField()),
            ],
        ),
    ]
